name: deploy

on:
  push:
    branches: [ docs ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Build 🔧
        run: |
          yarn install
          yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: master
          FOLDER: docs/.vitepress/dist
          CLEAN: true
