name: lint

on:
  push:
    branches: [ docs ]
  pull_request:
    branches: [ docs ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Lint 🔧
        run: |
          yarn install
          yarn lint
